[workspace]
resolver = "2"
members = [
    ".",
    "contextd-client",
    "bridges/openrgb-contextd-bridge",
]
exclude = [
    "packaging/**",
    "build/**",
]

[package]
name = "contextd"
version = "0.9.1"
edition = "2024"
authors = ["Shane Fagan <shane@performativenonsense.com>"]
homepage = "https://github.com/shanefagan/contextd"
repository = "https://github.com/shanefagan/contextd"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
varlink = "13.0"
udev = "0.9" # For future hardware inventory
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
serde_derive = "1.0"
rusqlite = { version = "0.39", features = ["bundled"] }
sysinfo = "0.39"
libc = "0.2"
toml = "1.1.2"
once_cell = "1.21.4"
threadpool = "1.8.1"

[build-dependencies]
varlink_generator = "13.0"
