#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use serde_derive::{Deserialize, Serialize};
use std::io::BufRead;
use std::sync::{Arc, RwLock};
use varlink::{self, CallTrait};
#[allow(dead_code)]
#[derive(Clone, PartialEq, Debug)]
#[allow(clippy::enum_variant_names)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
    InvalidColorValue(Option<InvalidColorValue_Args>),
    InvalidMatrixSize(Option<InvalidMatrixSize_Args>),
    MatrixTooLarge(Option<MatrixTooLarge_Args>),
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ErrorKind::Varlink_Error => write!(f, "Varlink Error"),
            ErrorKind::VarlinkReply_Error => write!(f, "Varlink error reply"),
            ErrorKind::InvalidColorValue(v) => write!(
                f,
                "com.performativenonsense.contextd.rgb.Control.InvalidColorValue: {:#?}",
                v
            ),
            ErrorKind::InvalidMatrixSize(v) => write!(
                f,
                "com.performativenonsense.contextd.rgb.Control.InvalidMatrixSize: {:#?}",
                v
            ),
            ErrorKind::MatrixTooLarge(v) => write!(
                f,
                "com.performativenonsense.contextd.rgb.Control.MatrixTooLarge: {:#?}",
                v
            ),
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    #[allow(dead_code)]
    pub fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Error(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}
#[allow(dead_code)]
pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Error(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Error(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}
#[allow(dead_code)]
impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .map(|e| e.kind());
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        match e {
            varlink::Reply { error: Some(t), .. }
                if t == "com.performativenonsense.contextd.rgb.Control.InvalidColorValue" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::InvalidColorValue(v),
                        Err(_) => ErrorKind::InvalidColorValue(None),
                    },
                    _ => ErrorKind::InvalidColorValue(None),
                }
            }
            varlink::Reply { error: Some(t), .. }
                if t == "com.performativenonsense.contextd.rgb.Control.InvalidMatrixSize" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::InvalidMatrixSize(v),
                        Err(_) => ErrorKind::InvalidMatrixSize(None),
                    },
                    _ => ErrorKind::InvalidMatrixSize(None),
                }
            }
            varlink::Reply { error: Some(t), .. }
                if t == "com.performativenonsense.contextd.rgb.Control.MatrixTooLarge" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::MatrixTooLarge(v),
                        Err(_) => ErrorKind::MatrixTooLarge(None),
                    },
                    _ => ErrorKind::MatrixTooLarge(None),
                }
            }
            _ => ErrorKind::VarlinkReply_Error,
        }
    }
}
#[allow(dead_code)]
pub trait VarlinkCallError: varlink::CallTrait {
    fn reply_invalid_color_value(
        &mut self,
        r#component: String,
        r#value: i64,
    ) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "com.performativenonsense.contextd.rgb.Control.InvalidColorValue",
            Some(
                serde_json::to_value(InvalidColorValue_Args {
                    r#component,
                    r#value,
                })
                .map_err(varlink::map_context!())?,
            ),
        ))
    }
    fn reply_invalid_matrix_size(
        &mut self,
        r#width: i64,
        r#height: i64,
        r#data_len: i64,
    ) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "com.performativenonsense.contextd.rgb.Control.InvalidMatrixSize",
            Some(
                serde_json::to_value(InvalidMatrixSize_Args {
                    r#width,
                    r#height,
                    r#data_len,
                })
                .map_err(varlink::map_context!())?,
            ),
        ))
    }
    fn reply_matrix_too_large(&mut self, r#max_pixels: i64) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "com.performativenonsense.contextd.rgb.Control.MatrixTooLarge",
            Some(
                serde_json::to_value(MatrixTooLarge_Args { r#max_pixels })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
}
impl VarlinkCallError for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#Color {
    pub r#r: i64,
    pub r#g: i64,
    pub r#b: i64,
    pub r#a: i64,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#Matrix {
    pub r#width: i64,
    pub r#height: i64,
    pub r#data: Vec<Color>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct InvalidColorValue_Args {
    pub r#component: String,
    pub r#value: i64,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct InvalidMatrixSize_Args {
    pub r#width: i64,
    pub r#height: i64,
    pub r#data_len: i64,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct MatrixTooLarge_Args {
    pub r#max_pixels: i64,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct SetLightingContext_Reply {}
impl varlink::VarlinkReply for SetLightingContext_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct SetLightingContext_Args {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#main_color: Option<Color>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#matrix: Option<Matrix>,
}
#[allow(dead_code)]
pub trait Call_SetLightingContext: VarlinkCallError {
    fn reply(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
    }
}
impl Call_SetLightingContext for varlink::Call<'_> {}
#[allow(dead_code)]
pub trait VarlinkInterface {
    fn set_lighting_context(
        &self,
        call: &mut dyn Call_SetLightingContext,
        r#main_color: Option<Color>,
        r#matrix: Option<Matrix>,
    ) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}
#[allow(dead_code)]
pub trait VarlinkClientInterface {
    fn set_lighting_context(
        &mut self,
        r#main_color: Option<Color>,
        r#matrix: Option<Matrix>,
    ) -> varlink::MethodCall<SetLightingContext_Args, SetLightingContext_Reply, Error>;
}
#[allow(dead_code)]
pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
}
impl VarlinkClient {
    #[allow(dead_code)]
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient { connection }
    }
}
impl VarlinkClientInterface for VarlinkClient {
    fn set_lighting_context(
        &mut self,
        r#main_color: Option<Color>,
        r#matrix: Option<Matrix>,
    ) -> varlink::MethodCall<SetLightingContext_Args, SetLightingContext_Reply, Error> {
        varlink::MethodCall::<SetLightingContext_Args, SetLightingContext_Reply, Error>::new(
            self.connection.clone(),
            "com.performativenonsense.contextd.rgb.Control.SetLightingContext",
            SetLightingContext_Args {
                r#main_color,
                r#matrix,
            },
        )
    }
}
#[allow(dead_code)]
pub struct VarlinkInterfaceProxy {
    inner: Box<dyn VarlinkInterface + Send + Sync>,
}
#[allow(dead_code)]
pub fn new(inner: Box<dyn VarlinkInterface + Send + Sync>) -> VarlinkInterfaceProxy {
    VarlinkInterfaceProxy { inner }
}
impl varlink::Interface for VarlinkInterfaceProxy {
    fn get_description(&self) -> &'static str {
        "interface com.performativenonsense.contextd.rgb.Control\n\n# RGBA Color representation\ntype Color (\n  r: int,\n  g: int,\n  b: int,\n  a: int\n)\n\n# A rectangular matrix of colors (width x height)\ntype Matrix (\n  width: int,\n  height: int,\n  data: []Color\n)\n\n# Sets the current lighting context.\nmethod SetLightingContext(\n  main_color: ?Color,\n  matrix: ?Matrix\n) -> ()\n\n# The Matrix size requested is too large\nerror MatrixTooLarge(max_pixels: int)\n\n# The Matrix data length does not match width * height\nerror InvalidMatrixSize(width: int, height: int, data_len: int)\n\n# A color component value is outside the valid range (0-255)\nerror InvalidColorValue(component: string, value: int)\n"
    }
    fn get_name(&self) -> &'static str {
        "com.performativenonsense.contextd.rgb.Control"
    }
    fn call_upgraded(
        &self,
        call: &mut varlink::Call,
        bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        self.inner.call_upgraded(call, bufreader)
    }
    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "com.performativenonsense.contextd.rgb.Control.SetLightingContext" => {
                if let Some(args) = req.parameters.clone() {
                    let args: SetLightingContext_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner.set_lighting_context(
                        call as &mut dyn Call_SetLightingContext,
                        args.r#main_color,
                        args.r#matrix,
                    )
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            m => call.reply_method_not_found(String::from(m)),
        }
    }
}
