#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use serde_derive::{Deserialize, Serialize};
use std::io::BufRead;
use std::sync::{Arc, RwLock};
use varlink::{self, CallTrait};
#[allow(dead_code)]
#[derive(Clone, PartialEq, Debug)]
#[allow(clippy::enum_variant_names)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ErrorKind::Varlink_Error => write!(f, "Varlink Error"),
            ErrorKind::VarlinkReply_Error => write!(f, "Varlink error reply"),
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    #[allow(dead_code)]
    pub fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Error(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}
#[allow(dead_code)]
pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Error(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Error(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}
#[allow(dead_code)]
impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .map(|e| e.kind());
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        match e {
            _ => ErrorKind::VarlinkReply_Error,
        }
    }
}
#[allow(dead_code)]
pub trait VarlinkCallError: varlink::CallTrait {}
impl VarlinkCallError for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#Controller {
    pub r#name: String,
    pub r#version: Option<String>,
    pub r#pid: i64,
    pub r#description: Option<String>,
    pub r#website: Option<String>,
    pub r#capabilities: Vec<String>,
    pub r#interested_devices: Vec<String>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#Device {
    pub r#name: String,
    pub r#vendor: String,
    pub r#vendor_id: String,
    pub r#product_id: String,
    pub r#bus_type: String,
    pub r#path: String,
    pub r#classes: Vec<String>,
    pub r#has_uaccess: bool,
    pub r#controllers: Vec<Controller>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#Diagnostics {
    pub r#vulkan_supported: bool,
    pub r#vulkan_version: Option<String>,
    pub r#opengl_supported: bool,
    pub r#ram_total: i64,
    pub r#cpu_model: String,
    pub r#cpu_count: i64,
    pub r#gpus: Vec<Gpu>,
    pub r#kernel_version: String,
    pub r#last_updated: i64,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#Game {
    pub r#name: String,
    pub r#id: Option<String>,
    pub r#source: String,
    pub r#pid: Option<i64>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#Gpu {
    pub r#name: String,
    pub r#vendor: String,
    pub r#driver: String,
    pub r#vram_total: i64,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GetActiveGame_Reply {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#game: Option<Game>,
}
impl varlink::VarlinkReply for GetActiveGame_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GetActiveGame_Args {}
#[allow(dead_code)]
pub trait Call_GetActiveGame: VarlinkCallError {
    fn reply(&mut self, r#game: Option<Game>) -> varlink::Result<()> {
        self.reply_struct(GetActiveGame_Reply { r#game }.into())
    }
}
impl Call_GetActiveGame for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GetDiagnostics_Reply {
    pub r#diagnostics: Diagnostics,
}
impl varlink::VarlinkReply for GetDiagnostics_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GetDiagnostics_Args {}
#[allow(dead_code)]
pub trait Call_GetDiagnostics: VarlinkCallError {
    fn reply(&mut self, r#diagnostics: Diagnostics) -> varlink::Result<()> {
        self.reply_struct(GetDiagnostics_Reply { r#diagnostics }.into())
    }
}
impl Call_GetDiagnostics for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ListControllers_Reply {
    pub r#controllers: Vec<Controller>,
}
impl varlink::VarlinkReply for ListControllers_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ListControllers_Args {}
#[allow(dead_code)]
pub trait Call_ListControllers: VarlinkCallError {
    fn reply(&mut self, r#controllers: Vec<Controller>) -> varlink::Result<()> {
        self.reply_struct(ListControllers_Reply { r#controllers }.into())
    }
}
impl Call_ListControllers for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ListDevices_Reply {
    pub r#devices: Vec<Device>,
}
impl varlink::VarlinkReply for ListDevices_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ListDevices_Args {}
#[allow(dead_code)]
pub trait Call_ListDevices: VarlinkCallError {
    fn reply(&mut self, r#devices: Vec<Device>) -> varlink::Result<()> {
        self.reply_struct(ListDevices_Reply { r#devices }.into())
    }
}
impl Call_ListDevices for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ListInstalledGames_Reply {
    pub r#games: Vec<Game>,
}
impl varlink::VarlinkReply for ListInstalledGames_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ListInstalledGames_Args {}
#[allow(dead_code)]
pub trait Call_ListInstalledGames: VarlinkCallError {
    fn reply(&mut self, r#games: Vec<Game>) -> varlink::Result<()> {
        self.reply_struct(ListInstalledGames_Reply { r#games }.into())
    }
}
impl Call_ListInstalledGames for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ListRGBDevices_Reply {
    pub r#devices: Vec<Device>,
}
impl varlink::VarlinkReply for ListRGBDevices_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ListRGBDevices_Args {}
#[allow(dead_code)]
pub trait Call_ListRGBDevices: VarlinkCallError {
    fn reply(&mut self, r#devices: Vec<Device>) -> varlink::Result<()> {
        self.reply_struct(ListRGBDevices_Reply { r#devices }.into())
    }
}
impl Call_ListRGBDevices for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct RegisterController_Reply {}
impl varlink::VarlinkReply for RegisterController_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct RegisterController_Args {
    pub r#controller: Controller,
}
#[allow(dead_code)]
pub trait Call_RegisterController: VarlinkCallError {
    fn reply(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
    }
}
impl Call_RegisterController for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct UnregisterController_Reply {}
impl varlink::VarlinkReply for UnregisterController_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct UnregisterController_Args {
    pub r#pid: i64,
}
#[allow(dead_code)]
pub trait Call_UnregisterController: VarlinkCallError {
    fn reply(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
    }
}
impl Call_UnregisterController for varlink::Call<'_> {}
#[allow(dead_code)]
pub trait VarlinkInterface {
    fn get_active_game(&self, call: &mut dyn Call_GetActiveGame) -> varlink::Result<()>;
    fn get_diagnostics(&self, call: &mut dyn Call_GetDiagnostics) -> varlink::Result<()>;
    fn list_controllers(&self, call: &mut dyn Call_ListControllers) -> varlink::Result<()>;
    fn list_devices(&self, call: &mut dyn Call_ListDevices) -> varlink::Result<()>;
    fn list_installed_games(&self, call: &mut dyn Call_ListInstalledGames) -> varlink::Result<()>;
    fn list_rgbdevices(&self, call: &mut dyn Call_ListRGBDevices) -> varlink::Result<()>;
    fn register_controller(
        &self,
        call: &mut dyn Call_RegisterController,
        r#controller: Controller,
    ) -> varlink::Result<()>;
    fn unregister_controller(
        &self,
        call: &mut dyn Call_UnregisterController,
        r#pid: i64,
    ) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}
#[allow(dead_code)]
pub trait VarlinkClientInterface {
    fn get_active_game(
        &mut self,
    ) -> varlink::MethodCall<GetActiveGame_Args, GetActiveGame_Reply, Error>;
    fn get_diagnostics(
        &mut self,
    ) -> varlink::MethodCall<GetDiagnostics_Args, GetDiagnostics_Reply, Error>;
    fn list_controllers(
        &mut self,
    ) -> varlink::MethodCall<ListControllers_Args, ListControllers_Reply, Error>;
    fn list_devices(&mut self) -> varlink::MethodCall<ListDevices_Args, ListDevices_Reply, Error>;
    fn list_installed_games(
        &mut self,
    ) -> varlink::MethodCall<ListInstalledGames_Args, ListInstalledGames_Reply, Error>;
    fn list_rgbdevices(
        &mut self,
    ) -> varlink::MethodCall<ListRGBDevices_Args, ListRGBDevices_Reply, Error>;
    fn register_controller(
        &mut self,
        r#controller: Controller,
    ) -> varlink::MethodCall<RegisterController_Args, RegisterController_Reply, Error>;
    fn unregister_controller(
        &mut self,
        r#pid: i64,
    ) -> varlink::MethodCall<UnregisterController_Args, UnregisterController_Reply, Error>;
}
#[allow(dead_code)]
pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
}
impl VarlinkClient {
    #[allow(dead_code)]
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient { connection }
    }
}
impl VarlinkClientInterface for VarlinkClient {
    fn get_active_game(
        &mut self,
    ) -> varlink::MethodCall<GetActiveGame_Args, GetActiveGame_Reply, Error> {
        varlink::MethodCall::<GetActiveGame_Args, GetActiveGame_Reply, Error>::new(
            self.connection.clone(),
            "com.performativenonsense.contextd.GetActiveGame",
            GetActiveGame_Args {},
        )
    }
    fn get_diagnostics(
        &mut self,
    ) -> varlink::MethodCall<GetDiagnostics_Args, GetDiagnostics_Reply, Error> {
        varlink::MethodCall::<GetDiagnostics_Args, GetDiagnostics_Reply, Error>::new(
            self.connection.clone(),
            "com.performativenonsense.contextd.GetDiagnostics",
            GetDiagnostics_Args {},
        )
    }
    fn list_controllers(
        &mut self,
    ) -> varlink::MethodCall<ListControllers_Args, ListControllers_Reply, Error> {
        varlink::MethodCall::<ListControllers_Args, ListControllers_Reply, Error>::new(
            self.connection.clone(),
            "com.performativenonsense.contextd.ListControllers",
            ListControllers_Args {},
        )
    }
    fn list_devices(&mut self) -> varlink::MethodCall<ListDevices_Args, ListDevices_Reply, Error> {
        varlink::MethodCall::<ListDevices_Args, ListDevices_Reply, Error>::new(
            self.connection.clone(),
            "com.performativenonsense.contextd.ListDevices",
            ListDevices_Args {},
        )
    }
    fn list_installed_games(
        &mut self,
    ) -> varlink::MethodCall<ListInstalledGames_Args, ListInstalledGames_Reply, Error> {
        varlink::MethodCall::<ListInstalledGames_Args, ListInstalledGames_Reply, Error>::new(
            self.connection.clone(),
            "com.performativenonsense.contextd.ListInstalledGames",
            ListInstalledGames_Args {},
        )
    }
    fn list_rgbdevices(
        &mut self,
    ) -> varlink::MethodCall<ListRGBDevices_Args, ListRGBDevices_Reply, Error> {
        varlink::MethodCall::<ListRGBDevices_Args, ListRGBDevices_Reply, Error>::new(
            self.connection.clone(),
            "com.performativenonsense.contextd.ListRGBDevices",
            ListRGBDevices_Args {},
        )
    }
    fn register_controller(
        &mut self,
        r#controller: Controller,
    ) -> varlink::MethodCall<RegisterController_Args, RegisterController_Reply, Error> {
        varlink::MethodCall::<RegisterController_Args, RegisterController_Reply, Error>::new(
            self.connection.clone(),
            "com.performativenonsense.contextd.RegisterController",
            RegisterController_Args { r#controller },
        )
    }
    fn unregister_controller(
        &mut self,
        r#pid: i64,
    ) -> varlink::MethodCall<UnregisterController_Args, UnregisterController_Reply, Error> {
        varlink::MethodCall::<UnregisterController_Args, UnregisterController_Reply, Error>::new(
            self.connection.clone(),
            "com.performativenonsense.contextd.UnregisterController",
            UnregisterController_Args { r#pid },
        )
    }
}
#[allow(dead_code)]
pub struct VarlinkInterfaceProxy {
    inner: Box<dyn VarlinkInterface + Send + Sync>,
}
#[allow(dead_code)]
pub fn new(inner: Box<dyn VarlinkInterface + Send + Sync>) -> VarlinkInterfaceProxy {
    VarlinkInterfaceProxy { inner }
}
impl varlink::Interface for VarlinkInterfaceProxy {
    fn get_description(&self) -> &'static str {
        "interface com.performativenonsense.contextd\n\n\n# Hardware device type\ntype Device (\n  name: string,\n  vendor: string,\n  vendor_id: string,\n  product_id: string,\n  bus_type: string,\n  path: string,\n  classes: []string,\n  has_uaccess: bool,\n  controllers: []Controller\n)\n\n# Hint about an application that can control hardware\ntype Controller (\n  name: string,\n  version: ?string,\n  pid: int,\n  description: ?string,\n  website: ?string,\n  capabilities: []string,\n  interested_devices: []string\n)\n\n# Game information\ntype Game (\n  name: string,\n  id: ?string,\n  source: string,\n  pid: ?int\n)\n\n# GPU Information\ntype Gpu (\n  name: string,\n  vendor: string,\n  driver: string,\n  vram_total: int\n)\n\n# System Diagnostics\ntype Diagnostics (\n  vulkan_supported: bool,\n  vulkan_version: ?string,\n  opengl_supported: bool,\n  ram_total: int,\n  cpu_model: string,\n  cpu_count: int,\n  gpus: []Gpu,\n  kernel_version: string,\n  last_updated: int # Unix timestamp\n)\n\n# Returns the currently active game, if any.\nmethod GetActiveGame() -> (game: ?Game)\n\n# Lists all installed games detected on the system.\nmethod ListInstalledGames() -> (games: []Game)\n\n# Lists all connected keyboards, mice, and controllers.\nmethod ListDevices() -> (devices: []Device)\n\n# Lists all RGB controllers, lighting strips, and fans.\nmethod ListRGBDevices() -> (devices: []Device)\n\n# Returns diagnostic information for the system.\nmethod GetDiagnostics() -> (diagnostics: Diagnostics)\n\n# Registers or updates a controller hint.\nmethod RegisterController(controller: Controller) -> ()\n\n# Unregisters a controller hint.\nmethod UnregisterController(pid: int) -> ()\n\n# Lists all active controller hints.\nmethod ListControllers() -> (controllers: []Controller)\n\n"
    }
    fn get_name(&self) -> &'static str {
        "com.performativenonsense.contextd"
    }
    fn call_upgraded(
        &self,
        call: &mut varlink::Call,
        bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        self.inner.call_upgraded(call, bufreader)
    }
    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "com.performativenonsense.contextd.GetActiveGame" => self
                .inner
                .get_active_game(call as &mut dyn Call_GetActiveGame),
            "com.performativenonsense.contextd.GetDiagnostics" => self
                .inner
                .get_diagnostics(call as &mut dyn Call_GetDiagnostics),
            "com.performativenonsense.contextd.ListControllers" => self
                .inner
                .list_controllers(call as &mut dyn Call_ListControllers),
            "com.performativenonsense.contextd.ListDevices" => {
                self.inner.list_devices(call as &mut dyn Call_ListDevices)
            }
            "com.performativenonsense.contextd.ListInstalledGames" => self
                .inner
                .list_installed_games(call as &mut dyn Call_ListInstalledGames),
            "com.performativenonsense.contextd.ListRGBDevices" => self
                .inner
                .list_rgbdevices(call as &mut dyn Call_ListRGBDevices),
            "com.performativenonsense.contextd.RegisterController" => {
                if let Some(args) = req.parameters.clone() {
                    let args: RegisterController_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner.register_controller(
                        call as &mut dyn Call_RegisterController,
                        args.r#controller,
                    )
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            "com.performativenonsense.contextd.UnregisterController" => {
                if let Some(args) = req.parameters.clone() {
                    let args: UnregisterController_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner.unregister_controller(
                        call as &mut dyn Call_UnregisterController,
                        args.r#pid,
                    )
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            m => call.reply_method_not_found(String::from(m)),
        }
    }
}
