#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use serde_derive::{Deserialize, Serialize};
use std::io::BufRead;
use std::sync::{Arc, RwLock};
use varlink::{self, CallTrait};
#[allow(dead_code)]
#[derive(Clone, PartialEq, Debug)]
#[allow(clippy::enum_variant_names)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ErrorKind::Varlink_Error => write!(f, "Varlink Error"),
            ErrorKind::VarlinkReply_Error => write!(f, "Varlink error reply"),
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    #[allow(dead_code)]
    pub fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Error(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}
#[allow(dead_code)]
pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Error(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Error(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}
#[allow(dead_code)]
impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .map(|e| e.kind());
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        match e {
            _ => ErrorKind::VarlinkReply_Error,
        }
    }
}
#[allow(dead_code)]
pub trait VarlinkCallError: varlink::CallTrait {}
impl VarlinkCallError for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#Color {
    pub r#r: i64,
    pub r#g: i64,
    pub r#b: i64,
    pub r#a: i64,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#Matrix {
    pub r#size: i64,
    pub r#data: Vec<Color>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GetLightingContext_Reply {
    pub r#main_color: Color,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#matrix: Option<Matrix>,
}
impl varlink::VarlinkReply for GetLightingContext_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GetLightingContext_Args {}
#[allow(dead_code)]
pub trait Call_GetLightingContext: VarlinkCallError {
    fn reply(&mut self, r#main_color: Color, r#matrix: Option<Matrix>) -> varlink::Result<()> {
        self.reply_struct(
            GetLightingContext_Reply {
                r#main_color,
                r#matrix,
            }
            .into(),
        )
    }
}
impl Call_GetLightingContext for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct SubscribeLightingContext_Reply {
    pub r#main_color: Color,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#matrix: Option<Matrix>,
}
impl varlink::VarlinkReply for SubscribeLightingContext_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct SubscribeLightingContext_Args {}
#[allow(dead_code)]
pub trait Call_SubscribeLightingContext: VarlinkCallError {
    fn reply(&mut self, r#main_color: Color, r#matrix: Option<Matrix>) -> varlink::Result<()> {
        self.reply_struct(
            SubscribeLightingContext_Reply {
                r#main_color,
                r#matrix,
            }
            .into(),
        )
    }
}
impl Call_SubscribeLightingContext for varlink::Call<'_> {}
#[allow(dead_code)]
pub trait VarlinkInterface {
    fn get_lighting_context(&self, call: &mut dyn Call_GetLightingContext) -> varlink::Result<()>;
    fn subscribe_lighting_context(
        &self,
        call: &mut dyn Call_SubscribeLightingContext,
    ) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}
#[allow(dead_code)]
pub trait VarlinkClientInterface {
    fn get_lighting_context(
        &mut self,
    ) -> varlink::MethodCall<GetLightingContext_Args, GetLightingContext_Reply, Error>;
    fn subscribe_lighting_context(
        &mut self,
    ) -> varlink::MethodCall<SubscribeLightingContext_Args, SubscribeLightingContext_Reply, Error>;
}
#[allow(dead_code)]
pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
}
impl VarlinkClient {
    #[allow(dead_code)]
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient { connection }
    }
}
impl VarlinkClientInterface for VarlinkClient {
    fn get_lighting_context(
        &mut self,
    ) -> varlink::MethodCall<GetLightingContext_Args, GetLightingContext_Reply, Error> {
        varlink::MethodCall::<GetLightingContext_Args, GetLightingContext_Reply, Error>::new(
            self.connection.clone(),
            "com.performativenonsense.contextd.rgb.Observer.GetLightingContext",
            GetLightingContext_Args {},
        )
    }
    fn subscribe_lighting_context(
        &mut self,
    ) -> varlink::MethodCall<SubscribeLightingContext_Args, SubscribeLightingContext_Reply, Error>
    {
        varlink :: MethodCall :: < SubscribeLightingContext_Args , SubscribeLightingContext_Reply , Error > :: new (self . connection . clone () , "com.performativenonsense.contextd.rgb.Observer.SubscribeLightingContext" , SubscribeLightingContext_Args { })
    }
}
#[allow(dead_code)]
pub struct VarlinkInterfaceProxy {
    inner: Box<dyn VarlinkInterface + Send + Sync>,
}
#[allow(dead_code)]
pub fn new(inner: Box<dyn VarlinkInterface + Send + Sync>) -> VarlinkInterfaceProxy {
    VarlinkInterfaceProxy { inner }
}
impl varlink::Interface for VarlinkInterfaceProxy {
    fn get_description(&self) -> &'static str {
        "interface com.performativenonsense.contextd.rgb.Observer\n\n# RGBA Color representation\ntype Color (\n  r: int,\n  g: int,\n  b: int,\n  a: int\n)\n\n# A square matrix of colors (N x N)\ntype Matrix (\n  size: int,\n  data: []Color\n)\n\n# Returns the current ambient lighting context.\nmethod GetLightingContext() -> (\n  main_color: Color,\n  matrix: ?Matrix\n)\n\n# Subscribes to lighting context updates.\nmethod SubscribeLightingContext() -> (\n  main_color: Color,\n  matrix: ?Matrix\n)\n"
    }
    fn get_name(&self) -> &'static str {
        "com.performativenonsense.contextd.rgb.Observer"
    }
    fn call_upgraded(
        &self,
        call: &mut varlink::Call,
        bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        self.inner.call_upgraded(call, bufreader)
    }
    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "com.performativenonsense.contextd.rgb.Observer.GetLightingContext" => self
                .inner
                .get_lighting_context(call as &mut dyn Call_GetLightingContext),
            "com.performativenonsense.contextd.rgb.Observer.SubscribeLightingContext" => self
                .inner
                .subscribe_lighting_context(call as &mut dyn Call_SubscribeLightingContext),
            m => call.reply_method_not_found(String::from(m)),
        }
    }
}
